-- Active: 1683388537085@@127.0.0.1@5432@mvc_db
CREATE TABLE IF NOT EXISTS folders (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);